
    create table Canchas (
        id bigint generated by default as identity (start with 1),
        esta_iluminada boolean,
        nombre varchar(255),
        color_codigo bigint,
        primary key (id)
    )

    create table Colores (
        codigo bigint generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (codigo)
    )

    create table Constructores (
        codigo bigint generated by default as identity (start with 1),
        domicilio varchar(255),
        nombre varchar(255),
        primary key (codigo)
    )

    create table Jugadores (
        id bigint generated by default as identity (start with 1),
        apellido varchar(255),
        domicilio varchar(255),
        nacimiento varbinary(255),
        nombre varchar(255),
        telefono varchar(255),
        paleta_codigo bigint,
        primary key (id)
    )

    create table Paletas (
        codigo bigint generated by default as identity (start with 1),
        grosor varchar(255),
        nombre varchar(255),
        constructor_codigo bigint,
        paleta_codigo bigint,
        primary key (codigo)
    )

    create table Participacion (
        jugador_id bigint not null,
        partido_id bigint not null,
        paleta_codigo bigint,
        primary key (jugador_id, partido_id)
    )

    create table Partidos (
        id bigint generated by default as identity (start with 1),
        finPartido DATE,
        inicioPartido DATE,
        color_codigo bigint,
        jugador_reserva_id bigint,
        cancha_id bigint,
        primary key (id)
    )

    alter table Canchas 
        add constraint FK_g1bnp1vg9ta6vabbc7tp4pg3f 
        foreign key (color_codigo) 
        references Colores

    alter table Jugadores 
        add constraint FK_5gbyswonactruap7fg658p1ag 
        foreign key (paleta_codigo) 
        references Paletas

    alter table Paletas 
        add constraint FK_aivohyxjjprv4crotd9vqp1yl 
        foreign key (constructor_codigo) 
        references Constructores

    alter table Paletas 
        add constraint FK_fjpg0l580uxh4oy89o32caaad 
        foreign key (paleta_codigo) 
        references Colores

    alter table Participacion 
        add constraint FK_kn4arx2tpeomuc85mssxvngq0 
        foreign key (paleta_codigo) 
        references Paletas

    alter table Participacion 
        add constraint FK_fkdrcmjbfeubmhpki7fnildno 
        foreign key (partido_id) 
        references Partidos

    alter table Participacion 
        add constraint FK_9mvyrp3rpm1phaqux42y69tmu 
        foreign key (jugador_id) 
        references Jugadores

    alter table Partidos 
        add constraint FK_r785kjiji8u0tvs4e1a6xhjxe 
        foreign key (color_codigo) 
        references Colores

    alter table Partidos 
        add constraint FK_b6anbfvifxwyqyx2h4ev5i1sm 
        foreign key (jugador_reserva_id) 
        references Jugadores

    alter table Partidos 
        add constraint FK_euaoyb7bsul9ym4v8u23cix4f 
        foreign key (cancha_id) 
        references Canchas
